<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Station;
use App\Models\StationSession;
use App\Models\Line;
use App\Models\LineLog;
use App\Models\MealType;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

/**
 * ============================================================================
 * POS Controller
 * ============================================================================
 *
 * Handles POS authentication, health checks, and settings.
 *
 * ============================================================================
 */
class POSController extends Controller
{
    /**
     * POST /api/pos/login
     *
     * Authenticate user and return session token.
     *
     * Request:
     *   - username: string
     *   - password: string
     *   - deviceId: string (UUID generated by frontend)
     *   - browser: string (chrome, firefox, edge, safari)
     *   - isPrivate: boolean (incognito mode)
     *   - macAddress: string (optional, if available)
     *   - ipAddress: string (optional)
     */
    public function login(Request $request): JsonResponse
    {
        $request->validate([
            'username' => 'required|string',
            'password' => 'required|string',
            'deviceId' => 'required|string|max:50',
            'browser' => 'required|string|max:20',
            'isPrivate' => 'boolean',
            'macAddress' => 'nullable|string|size:17', // XX:XX:XX:XX:XX:XX
            'ipAddress' => 'nullable|string',
        ]);

        // Find user by username
        $user = User::where('fldUsername', $request->username)->first();

        if (!$user) {
            return response()->json([
                'success' => false,
                'error' => 'Invalid credentials',
            ], 401);
        }

        // Validate password (MD5)
        if (!$user->validatePassword($request->password)) {
            return response()->json([
                'success' => false,
                'error' => 'Invalid credentials',
            ], 401);
        }

        // Check if user is a line user
        if (!$user->fldLineUser) {
            return response()->json([
                'success' => false,
                'error' => 'User does not have line access',
            ], 403);
        }

        // Register/update station
        $station = Station::findOrCreateByDevice(
            $request->deviceId,
            $request->browser,
            $request->boolean('isPrivate', false),
            $request->macAddress,
            $request->ipAddress
        );

        // Revoke any existing sessions for this user (one station at a time)
        StationSession::revokeOtherSessionsForUser($user->fldUsername);

        // Build abilities from user's line access
        $abilities = ['pos-access'];
        $lineAccess = $user->fldLineAccess ?? [];

        foreach ($lineAccess as $lineCode) {
            $abilities[] = 'line:' . $lineCode;
        }

        if ($user->fldLineAccessAll) {
            $abilities[] = 'line:*';
        }

        if ($user->fldLineCloser) {
            $abilities[] = 'line-closer';
        }

        // Create new session
        $session = StationSession::createForUser($user, $station, $abilities);

        // Get user's available lines (excluding childcare) with sync info
        $lines = $user->posLines()->map(function ($line) {
            $lineLog = LineLog::where('fldMealType', $line->fldMealType)
                ->where('fldLineNum', $line->fldLineNum)
                ->where('fldLineDate', now()->toDateString())
                ->first();

            $syncInfo = $lineLog ? $lineLog->getSyncInfo() : [
                'totalStations' => 0,
                'syncedStations' => 0,
                'activeStations' => 0,
                'syncingStations' => 0,
                'abandonedStations' => 0,
                'readyToClose' => false,
            ];

            return [
                'code' => $line->lineCode,
                'mealType' => $line->fldMealType,
                'lineNum' => $line->fldLineNum,
                'description' => $line->fldDescription,
                'mealDescription' => $line->fldMealDescription ?? null,
                'isFRProgram' => (bool) ($line->fldIsFRProgram ?? false),
                'status' => $line->todayStatus,
                'syncInfo' => $syncInfo,
            ];
        });

        // Get PosDevMode from system settings (key-value table)
        $devModeValue = DB::table('ww_system')
            ->where('fldParameter', 'PosDevMode')
            ->value('fldValue');
        $devMode = $devModeValue === 'true' || $devModeValue === '1';

        return response()->json([
            'success' => true,
            'token' => $session->fldToken,
            'isLineCloser' => (bool) $user->fldLineCloser,
            'devMode' => (bool) $devMode,
            'user' => [
                'id' => $user->fldUserId,
                'username' => $user->fldUsername,
                'firstName' => $user->fldFirstName,
                'lastName' => $user->fldLastName,
                'name' => $user->name,
                'hasAllLineAccess' => (bool) $user->fldLineAccessAll,
            ],
            'station' => [
                'id' => $station->fldId,
                'deviceId' => $station->fldDeviceId,
                'macAddress' => $station->fldMacAddress,
                'browser' => $station->fldBrowser,
                'isPrivate' => $station->fldIsPrivate,
            ],
            'lines' => $lines,
            'abilities' => $abilities,
        ]);
    }

    /**
     * POST /api/pos/logout
     *
     * Revoke the current session token.
     */
    public function logout(Request $request): JsonResponse
    {
        $token = $request->bearerToken();

        if (!$token) {
            return response()->json([
                'success' => false,
                'error' => 'No token provided',
            ], 401);
        }

        $session = StationSession::findByToken($token);

        if ($session) {
            $session->revoke();
        }

        return response()->json([
            'success' => true,
            'message' => 'Logged out successfully',
        ]);
    }

    /**
     * GET /api/pos/health
     *
     * Health check endpoint (public).
     */
    public function health(): JsonResponse
    {
        // Check database connection
        $dbOk = false;
        try {
            DB::connection()->getPdo();
            $dbOk = true;
        } catch (\Exception $e) {
            // Database not connected
        }

        return response()->json([
            'status' => $dbOk ? 'ok' : 'degraded',
            'database' => $dbOk,
            'timestamp' => now()->toIso8601String(),
        ]);
    }

    /**
     * GET /api/pos/lines
     *
     * Get available lines for the authenticated user.
     */
    public function lines(Request $request): JsonResponse
    {
        $token = $request->bearerToken();

        if (!$token) {
            return response()->json([
                'success' => false,
                'error' => 'No authorization token provided',
            ], 401);
        }

        $session = StationSession::findByToken($token);

        if (!$session) {
            return response()->json([
                'success' => false,
                'error' => 'Invalid or expired session',
            ], 401);
        }

        // Update last activity
        $session->updateLastActivity();

        $user = $session->user();

        if (!$user) {
            return response()->json([
                'success' => false,
                'error' => 'User not found',
            ], 404);
        }

        // Get user's available lines with sync info
        $lines = $user->posLines()->map(function ($line) {
            $lineLog = LineLog::where('fldMealType', $line->fldMealType)
                ->where('fldLineNum', $line->fldLineNum)
                ->where('fldLineDate', now()->toDateString())
                ->first();

            $syncInfo = $lineLog ? $lineLog->getSyncInfo() : [
                'totalStations' => 0,
                'syncedStations' => 0,
                'activeStations' => 0,
                'syncingStations' => 0,
                'abandonedStations' => 0,
                'readyToClose' => false,
            ];

            return [
                'code' => $line->lineCode,
                'mealType' => $line->fldMealType,
                'lineNum' => $line->fldLineNum,
                'description' => $line->fldDescription,
                'mealDescription' => $line->fldMealDescription ?? null,
                'isFRProgram' => (bool) ($line->fldIsFRProgram ?? false),
                'status' => $line->todayStatus,
                'syncInfo' => $syncInfo,
            ];
        });

        return response()->json([
            'success' => true,
            'isLineCloser' => (bool) $user->fldLineCloser,
            'lines' => $lines,
        ]);
    }

    /**
     * GET /api/pos/lines/{mealType}/{lineNum}/settings
     *
     * Get full settings for a specific line.
     */
    public function lineSettings(Request $request, string $mealType, int $lineNum): JsonResponse
    {
        $token = $request->bearerToken();

        if (!$token) {
            return response()->json([
                'success' => false,
                'error' => 'No authorization token provided',
            ], 401);
        }

        $session = StationSession::findByToken($token);

        if (!$session) {
            return response()->json([
                'success' => false,
                'error' => 'Invalid or expired session',
            ], 401);
        }

        // Check if user has access to this line
        $lineCode = $mealType . $lineNum;
        if (!$session->hasAbility('line:*') && !$session->hasAbility('line:' . $lineCode)) {
            return response()->json([
                'success' => false,
                'error' => 'Access denied to this line',
            ], 403);
        }

        // Update last activity
        $session->updateLastActivity();

        // Get line definition
        $line = Line::findByCode($lineCode);
        if (!$line) {
            return response()->json([
                'success' => false,
                'error' => 'Line not found',
            ], 404);
        }

        // Get meal type info
        $mealTypeInfo = MealType::where('fldMealType', $mealType)->first();

        // Build settings from ww_system (global) + ww_system_lines (line-specific)
        $settings = $this->buildLineSettings($mealType, $lineNum);

        // Static line info (doesn't change day to day)
        $lineInfo = [
            'mealType' => $mealType,
            'lineNum' => $lineNum,
            'lineCode' => $mealType . $lineNum,
            'description' => $line->fldDescription,
            'isFRProgram' => (bool) ($mealTypeInfo->fldIsFRProgram ?? false),
        ];

        return response()->json([
            'success' => true,
            'settings' => $settings,
            'line' => $lineInfo,
        ]);
    }

    /**
     * POST /api/pos/lines/{mealType}/{lineNum}/open
     *
     * Open a line for the current session.
     */
    public function openLine(Request $request, string $mealType, int $lineNum): JsonResponse
    {
        $token = $request->bearerToken();

        if (!$token) {
            return response()->json([
                'success' => false,
                'error' => 'No authorization token provided',
            ], 401);
        }

        $session = StationSession::findByToken($token);

        if (!$session) {
            return response()->json([
                'success' => false,
                'error' => 'Invalid or expired session',
            ], 401);
        }

        // Check if user has access to this line
        $lineCode = $mealType . $lineNum;
        if (!$session->hasAbility('line:*') && !$session->hasAbility('line:' . $lineCode)) {
            return response()->json([
                'success' => false,
                'error' => 'Access denied to this line',
            ], 403);
        }

        // Get line definition
        $line = Line::findByCode($lineCode);
        if (!$line) {
            return response()->json([
                'success' => false,
                'error' => 'Line not found',
            ], 404);
        }

        // Get or create today's line log
        $lineLog = LineLog::findOrCreateForToday($mealType, $lineNum);

        // Check if already closed
        if ($lineLog->isClosed()) {
            return response()->json([
                'success' => false,
                'error' => 'Line has already been closed for today',
            ], 409);
        }

        // Open the line if not already open
        $user = $session->user();
        if (!$lineLog->fldOpenDate) {
            $lineLog->update([
                'fldOpenDate' => now(),
                'fldOpenUser' => $user->fldUserId,
            ]);
        }

        // Link this session to the line log
        $session->update([
            'fldLineLogId' => $lineLog->fldId,
        ]);

        // Update last activity
        $session->updateLastActivity();

        // Get meal type info
        $mealTypeInfo = MealType::where('fldMealType', $mealType)->first();

        // Build settings
        $settings = $this->buildLineSettings($mealType, $lineNum);

        // Static line info (doesn't change day to day)
        $lineInfo = [
            'mealType' => $mealType,
            'lineNum' => $lineNum,
            'lineCode' => $mealType . $lineNum,
            'description' => $line->fldDescription,
            'isFRProgram' => (bool) ($mealTypeInfo->fldIsFRProgram ?? false),
        ];

        // Get sync info
        $syncInfo = $lineLog->getSyncInfo();

        // Daily line log/session info
        $lineLogData = [
            'id' => $lineLog->fldId,
            'stationSessionId' => $session->fldId,  // Unique per station - for syncKey generation
            'lineDate' => $lineLog->fldLineDate->toDateString(),
            'status' => $lineLog->status,
            'syncInfo' => $syncInfo,
        ];

        return response()->json([
            'success' => true,
            'settings' => $settings,
            'line' => $lineInfo,
            'lineLog' => $lineLogData,
        ]);
    }

    /**
     * Get all POS line settings with their hardcoded defaults
     * These are the settings the Vue POS app expects
     */
    private function getLineSettingsDefaults(): array
    {
        return [
            // =================================================================
            // BALANCE & PAYMENT SETTINGS
            // =================================================================
            'LowBalMsg' => true,                    // Show low balance warning
            'PosLowBalance' => 5.00,                // Low balance threshold ($)
            'PosShowBalance' => 1,                  // 0=Off, 1=Always, 2=Below Threshold
            'PosReqPayZero' => true,                // Require payment if balance below zero
            'PosReqPayCutoff' => true,              // Require payment if below cutoff
            'PosReqPayLimit' => true,               // Require payment if daily limit reached
            'PaymentDueMode' => 'TotalSale',        // 'TotalSale' or 'CalculatedBalance'
            'PosCutoffBalance' => -10.00,           // Cutoff balance threshold ($)
            'PayNotificationsDisabled' => false,    // Disable payment notifications

            // =================================================================
            // STUDENT MEAL SETTINGS
            // =================================================================
            'PosReqFreeStuMeal' => true,            // Free students get one meal
            'PosReqRedStuMeal' => true,             // Reduced students get one meal
            'PosReqPaidStuMeal' => false,           // Paid students get one meal
            'PosFirstMealInStuLimit' => true,       // First meal counts toward daily limit
            'PosAllowCashMeal' => false,            // Allow cash customers to buy meals

            // =================================================================
            // A LA CARTE & SECONDS
            // =================================================================
            'PreventSeconds' => false,              // Hide L/B/A after first reimbursable
            'DisableAlaCarteOn' => false,           // Hide a la carte below balance threshold
            'DisableAlaCarteThr' => 0.00,           // Balance threshold for a la carte

            // =================================================================
            // OVERRIDE
            // =================================================================
            'PosAllowOverride' => false,            // Show Override button
            'PosShowLowFree' => true,               // Show low balance for Free students

            // =================================================================
            // DISPLAY & UI
            // =================================================================
            'PosDefShowComment2' => true,           // Show comment line 2
            'PosDefSoundOn' => true,                // Enable sounds
            'PosStudentPhotos' => true,             // Show student photos
            'PosDefMsgTextSize' => 0,               // Message text size (0=default)

            // =================================================================
            // MESSAGE DISPLAY
            // =================================================================
            'EatenMsg' => '1',                      // 1=Always, 2=Message Only, 3=Hidden
            'StuLimMsg' => '1',                     // 1=Always Show, 2=Hidden
            'BirthdayMessage' => true,              // Play birthday sound/message
            'PosDefaultHappyBirthdayMessage' => 'Happy Birthday!',

            // =================================================================
            // ID ENTRY
            // =================================================================
            'PosDefIDType' => 'StudentId',          // Default ID type
            'PosDisableAutoID' => false,            // Require Enter key to submit ID
            'PosDisableIDClose' => false,           // Disable ID to close student

            // =================================================================
            // DEFAULT ITEMS (auto-add on student load)
            // =================================================================
            'DefItemsEnabled' => true,              // Auto-add default item
            'DefItemsSource' => 'U',                // 'S' = School, 'U' = Student
            'DefItemsCustom' => '',                 // School-defined default item ID

            // =================================================================
            // MILK SUBSTITUTION
            // =================================================================
            'ChgToMilkTgt' => '',                   // Milk item ID for swap (empty = disabled)

            // =================================================================
            // LAST SIBLING
            // =================================================================
            'PosLastSiblingOn' => false,            // Enable last sibling feature
            'PosLastSiblingMsg' => 'Last sibling - balance alert',

            // =================================================================
            // STUDENT TYPE MASKING (Privacy)
            // =================================================================
            'PosMaskingOn' => false,                // Hide real student type
            'PosMaskingP' => 'STD',                 // Alias for Paid students
            'PosMaskingR' => 'STD',                 // Alias for Reduced students
            'PosMaskingF' => 'STD',                 // Alias for Free students
            'PosMaskingE' => 'EMP',                 // Alias for Employee
            'PosMaskingS' => 'STF',                 // Alias for Staff

            // =================================================================
            // OVERT IDENTIFICATION
            // =================================================================
            'PosOvertIdentification' => true,       // Show student type openly

            // =================================================================
            // LINE SETTINGS
            // =================================================================
            'PosLineLoginTimeout' => 0,             // Inactivity timeout in minutes (0 = disabled)
            'IsCashLine' => false,                  // Cash-only line

            // =================================================================
            // DEFAULT STUDENT PERMISSIONS
            // =================================================================
            'DefStudentLinePermission' => true,     // Students can use line
            'DefStudentAlaCartePermission' => true, // Students can buy a la carte
            'DefStudentMilkPermission' => true,     // Students can buy milk
            'DefStudentDailyLimit' => 5.00,         // Default daily spending limit

            // =================================================================
            // DEFAULT STAFF PERMISSIONS
            // =================================================================
            'DefStaffLinePermission' => true,       // Staff can use line
            'DefStaffAlaCartePermission' => true,   // Staff can buy a la carte
            'DefStaffMilkPermission' => true,       // Staff can buy milk
            'DefStaffDailyLimit' => 10.00,          // Default daily spending limit

            // =================================================================
            // OPERATING HOURS
            // =================================================================
            'NormalStartTime' => '',                // HH:MM format (empty = no restriction)
            'NormalStopTime' => '',                 // HH:MM format (empty = no restriction)

            // =================================================================
            // QUEUE SETTINGS
            // =================================================================
            'queueEnabled' => false,                // Enable student queue
            'queueTimeout' => 5,                    // Queue timeout in minutes
            'autoClose' => true,                    // Auto-close student on new ID

            // =================================================================
            // TAB TITLES
            // =================================================================
            'PosDefTab1Title' => 'Tab 1',
            'PosDefTab2Title' => 'Tab 2',
            'PosDefTab3Title' => 'Tab 3',
            'PosDefTab4Title' => 'Tab 4',
            'PosDefTab5Title' => 'Tab 5',
            'PosDefTab6Title' => 'Tab 6',
            'PosDefTab7Title' => 'Tab 7',
            'PosDefTab8Title' => 'Tab 8',
            'PosDefTab9Title' => 'Tab 9',
            'PosDefTab10Title' => 'Tab 10',
        ];
    }

    /**
     * Build settings object from ww_system and ww_system_lines
     *
     * Priority: line-specific (ww_system_lines) > global (ww_system) > hardcoded defaults
     */
    private function buildLineSettings(string $mealType, int $lineNum): array
    {
        // Start with hardcoded defaults
        $defaults = $this->getLineSettingsDefaults();
        $settingKeys = array_keys($defaults);

        // Get global settings from ww_system
        $globalSettings = DB::table('ww_system')
            ->whereNotNull('fldParameter')
            ->whereIn('fldParameter', $settingKeys)
            ->pluck('fldValue', 'fldParameter')
            ->toArray();

        // Get line-specific settings from ww_system_lines
        $lineSettings = DB::table('ww_system_lines')
            ->where('fldMealType', $mealType)
            ->where('fldLineNum', $lineNum)
            ->whereNotNull('fldParameter')
            ->whereIn('fldParameter', $settingKeys)
            ->pluck('fldValue', 'fldParameter')
            ->toArray();

        // Merge: defaults < global < line-specific
        $settings = [];
        foreach ($defaults as $key => $defaultValue) {
            // Check line-specific first, then global, then default
            if (isset($lineSettings[$key])) {
                $settings[$key] = $this->convertSettingValue($lineSettings[$key], $defaultValue);
            } elseif (isset($globalSettings[$key])) {
                $settings[$key] = $this->convertSettingValue($globalSettings[$key], $defaultValue);
            } else {
                $settings[$key] = $defaultValue;
            }
        }

        // Build tabNames array for convenience
        $tabNames = [];
        for ($i = 1; $i <= 10; $i++) {
            $tabNames[$i] = $settings["PosDefTab{$i}Title"];
        }
        $settings['tabNames'] = $tabNames;

        return $settings;
    }

    /**
     * Convert a database value to the appropriate type based on the default value type
     */
    private function convertSettingValue($value, $defaultValue)
    {
        // Handle null
        if ($value === null) {
            return $defaultValue;
        }

        // Determine target type from default
        if (is_bool($defaultValue)) {
            // Convert various boolean representations
            if ($value === '1' || $value === 1 || $value === true || $value === 'true') {
                return true;
            }
            if ($value === '0' || $value === 0 || $value === false || $value === 'false' || $value === '2') {
                return false;
            }
            return (bool) $value;
        }

        if (is_int($defaultValue)) {
            return (int) $value;
        }

        if (is_float($defaultValue)) {
            return (float) $value;
        }

        // String - return as-is
        return $value;
    }
}
